# Generated by Django 5.1.3 on 2025-01-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
